import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";

import { Toaster } from "@/components/ui/sonner";
import { siteUrl } from "@/lib/site-url";

// Pretendard (KO + EN) via its variable dynamic-subset stylesheet; wired to
// --font-sans in globals.css. Geist Mono stays for code/packet display.
import "pretendard/dist/web/variable/pretendardvariable-dynamic-subset.css";
import "./globals.css";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    template: "%s | Sev",
    default: "Sev — Turn AI answers into project knowledge",
  },
  // Must match the landing description copy in app/page.tsx (SEO "본문 일치").
  description:
    "Sev turns your project's files, notes, and AI answers into reusable knowledge you can bring to any AI.",
  // Landing is bilingual (en + ko). True hreflang (alternates.languages) is
  // deferred until real /en·/ko routes exist (i18n routing, Day16) — pointing
  // hreflang at non-existent URLs would be worse than none.
  alternates: { canonical: "/" },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: siteUrl,
    siteName: "Sev",
    // og:image is generated by app/opengraph-image.tsx (file convention).
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <Toaster />
      </body>
    </html>
  );
}
